[package]
name = "tower-shot"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
hdrhistogram = "7.5.4"
shot-limit = { version = "0.1.0", path = "../shot-limit" }
tokio.workspace = true
tower.workspace = true

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }
futures.workspace = true
tokio = { version = "1.48.0", features = [ "test-util" ] }

[[bench]]
name = "limiters"
harness = false
